import{useEffect,useState}from'react';import{COMPARISON_DIMENSIONS,type ReferenceComparisonPayload,type ComparisonNote,type ComparisonFinding}from'../../shared/referenceComparison';
import './referenceComparison.css';
const labels={style:'美术风格',camera:'镜头构图',action:'动作',feedback:'操作反馈',rules:'玩法规则'};
const findings:Record<ComparisonFinding,string>={'unreviewed':'尚未判断',aligned:'证据支持一致',differs:'存在差异',adapted:'按选定方案改编','not-observable':'当前素材无法证明'};
export function ReferenceComparison({projectId}:{projectId:string;refreshSignal:number}){
 const[opened,setOpened]=useState(false),[refresh,setRefresh]=useState(0);
 const[data,setData]=useState<ReferenceComparisonPayload|null>(null),[error,setError]=useState(''),[reference,setReference]=useState(''),[capture,setCapture]=useState(''),[context,setContext]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const[notes,setNotes]=useState<ComparisonNote[]>(COMPARISON_DIMENSIONS.map(dimension=>({dimension,finding:'unreviewed',note:''})));
 useEffect(()=>{if(!opened)return;let live=true;setError('');void window.noobi.getReferenceComparison(projectId).then(p=>{if(!live)return;setData(p);setReference(p?.references[0]?.id??'');setCapture(p?.captures[0]?.sha256??'');setContext('');setNotice('');setNotes(COMPARISON_DIMENSIONS.map(dimension=>({dimension,finding:'unreviewed',note:''})));}).catch(e=>{if(live)setError(String(e));});return()=>{live=false}},[projectId,opened,refresh]);
 const ref=data?.references.find(r=>r.id===reference),shot=data?.captures.find(c=>c.sha256===capture);
 async function save(){if(!data||busy)return;setBusy(true);setError('');try{await window.noobi.saveReferenceComparison({projectId,buildId:data.build.buildId,referenceId:reference,captureHash:capture,cameraAndState:context,notes});const fresh=await window.noobi.getReferenceComparison(projectId);setData(fresh);setNotice('对照记录已保存；不会自动改变交付或真人体验验收。');}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <details className="reference-comparison" onToggle={e=>setOpened(e.currentTarget.open)}><summary>参考与实际画面对照</summary><div className="comparison-body"><button type="button" disabled={busy} onClick={()=>setRefresh(refresh+1)}>刷新构建证据（清空未保存填写）</button>
 {error&&<p role="alert">{error}</p>}{!data?<p>等待已选方案的参考图与真实试玩截图。先完成构建和试玩，才能对照。</p>:<>
 <div className="comparison-conclusions"><div><strong>运行可靠性</strong><span>{data.shortRunVerdict==='pass'?'短流程检查通过':'短流程仍需修复'}</span><small>不代表 30 分钟稳定性</small></div><div><strong>需求完整度</strong><span>按已选需求逐项核验</span><small>{data.requirements.length} 条要求</small></div><div><strong>视觉一致性</strong><span>{data.records.length?'已有手动对照记录':'等待逐项对照'}</span><small>不以运行分数替代</small></div><div><strong>玩家体验</strong><span>等待真人试玩</span><small>机器检查不等于满意度</small></div></div>
 <p>{data.currentSource?'当前源码匹配此构建':'这是历史构建；源码已变化，重新构建后再保存对照'} · {data.build.buildId.slice(0,8)} · {new Date(data.checkedAt).toLocaleString('zh-CN')}</p>
 <div className="comparison-pair"><figure><label>参考图<select aria-label="对照参考图" value={reference} onChange={e=>setReference(e.target.value)}>{data.references.map(r=><option key={r.id} value={r.id}>{r.name} · {r.purpose}</option>)}</select></label>{ref&&<img src={ref.thumbnail} alt={`原始参考：${ref.name}`}/>}<figcaption>保持原比例；图片不能证明未展示的规则。</figcaption></figure><figure><label>实际试玩画面<select aria-label="对照试玩截图" value={capture} onChange={e=>setCapture(e.target.value)}>{data.captures.map(c=><option key={c.sha256} value={c.sha256}>{c.name}</option>)}</select></label>{shot&&<img src={shot.thumbnail} alt={`实际试玩：${shot.name}`}/>}<figcaption>只展示宿主保存并校验过的构建截图。</figcaption></figure></div>
 <details><summary>查看方案依据和主动改编内容</summary><ul>{data.requirements.map((r,i)=><li key={i}>{r}</li>)}</ul>{data.referenceSpec&&<><p>镜头：{data.referenceSpec.camera}</p><p>风格：{data.referenceSpec.style}</p><h4>推断与未知</h4><ul>{[...data.referenceSpec.inferences,...data.referenceSpec.unknowns].map((r,i)=><li key={i}>{r}</li>)}</ul></>}</details>
 <label>镜头和状态是否可比较<textarea aria-label="镜头和状态对照说明" maxLength={2000} value={context} onChange={e=>setContext(e.target.value)} placeholder="例如：参考是远景，试玩是背面近景；先比较配色，轮廓需换到正面。"/></label>
 <div className="comparison-findings">{notes.map((n,i)=><div key={n.dimension}><label>{labels[n.dimension]}<select aria-label={`${labels[n.dimension]}对照结论`} value={n.finding} onChange={e=>setNotes(notes.map((v,j)=>i===j?{...v,finding:e.target.value as ComparisonFinding}:v))}>{Object.entries(findings).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><textarea aria-label={`${labels[n.dimension]}证据说明`} maxLength={2000} value={n.note} onChange={e=>setNotes(notes.map((v,j)=>i===j?{...v,note:e.target.value}:v))} placeholder="写明画面证据、实际行为或方案中同意的改编；看不到就注明无法证明。"/></div>)}</div>
 <button type="button" disabled={busy||!data.currentSource||!reference||!capture} onClick={()=>void save()}>{busy?'正在保存…':'保存对照记录'}</button>{notice&&<p role="status">{notice}</p>}
 {data.records.length>0&&<details><summary>已有对照记录（{data.records.length}）</summary>{data.records.map(r=><article key={r.id}><p>{new Date(r.createdAt).toLocaleString('zh-CN')} · 手动记录</p><p>{r.cameraAndState}</p><ul>{r.notes.map(n=><li key={n.dimension}>{labels[n.dimension]}：{findings[n.finding]}。{n.note}</li>)}</ul></article>)}</details>}
 </>}
 </div></details>;
}
